spring:
  application:
    name: EUREKA-SERVER
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
     defaultZone: http://localhost:1112/eureka/
    fetch-registry: false
    register-with-eureka: false



#server:
#  port: 1111
#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:1112/eureka/
#---
#server:
#  port: 1112
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:1111/eureka/